### ISSUE TITLE
 Tracking Issue for Benchmark App

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasmBoy#189]
* [x] Drop the first couple of frames to get rid of the huge performance spikes
* [x] Create module/module builds by configuring the Typescript and Babel configs.
* [x] Update benchmark to do Wasm vs. ES6 Modules Vs. ES5
* [x] Don't run code through closure compiler / make sure source maps are one to one
* [x] Analytics

Thanks for all the help @kristoferbaxter ! 😄

**Comment by torch2424** [comment]
So I made a ESNext support thing (See the [typescript compiler target option](https://www.typescriptlang.org/docs/handbook/compiler-options.html)) in the rollup config for Wasm vs. ES6 Modules Vs. ES5. Where, ES6 modules would represent ESNEXT.

However, the difference is negligible:

**Standard Default Typescript ES output:**
<img width="563" alt="screen shot 2018-12-02 at 12 41 40 am" src="https://user-images.githubusercontent.com/1448289/49337673-a928f500-f5cb-11e8-925c-abe96996e798.png">

**ESNext:**
<img width="563" alt="screen shot 2018-12-02 at 12 45 00 am" src="https://user-images.githubusercontent.com/1448289/49337675-acbc7c00-f5cb-11e8-9252-63a4006ec5e4.png">

And implementing a third core would take a bunch of work. Thus, not going to implement here 😢 

Also, in terms of why there isn't much difference, it's because I am not doing a lot of Built in JS stuff in AssemblyScript, since Assemblyscript doesn't support it. For Example, I don't do any arrow functions, or something like [array forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach), since I am not using any arrays. The only real change we get in our case, is just things like ES6 classes and let/const vs. var.

**Comment by torch2424** [comment]
Though, it is worth running through closure compiler:

<img width="558" alt="screen shot 2018-12-02 at 1 03 25 am" src="https://user-images.githubusercontent.com/1448289/49337811-19d11100-f5ce-11e8-9117-42c560107f84.png">
