### ISSUE TITLE
WasmBoy 1.0 GB/GBC Roadmap

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasmBoy#197]
Been working on this project for almost a year now, and want to take a break. Will definitely be handling other things while completing this roadmap. Once this hits 1.0, will try and let the project sit for a bit before doing any more ports or anything like that.

# Phase 1 (Starting the Roadmap)

* [ ] Add this roadmap to the README

# Phase 2 (Immediate TAS issues)

* [ ] Fix remaining Blarggs timing tests (interrupt timing)
* [ ] #190
* [ ] #162

# Phase 3 (Benchmarking App)

* [ ] #189

# Phase 4 (Debugger)

* [ ] #168
* [ ] #143  
* [ ] #170 
* [ ] #46 
* [ ] #47 
* [ ] #48 
* [ ] #44 
* [ ] #43 
* [ ] #45 
* [ ] #196 
* [ ] #93 
* [ ] #96 
* [ ] #186 

# Phase 5 (Remaining MVP Core Work)

* [ ] #35 / Get horizontal scroll working.
* [ ] #83 
* [ ] #191 
* [ ] #92 
* Pass blarggs cgb_sound test
* look through the Pandocs and gbdev wiki for additional issues 

# Phase 6 (More Tests)

* Any more remaining important blargg tests.
* Some more mooneye tests.

# Phase 7 (Game Compatibility/Accuracy)

* [ ] #142 
* [ ] #49 
* [ ] #60 
* [ ] #146 
* [ ] Get Is that a Demo in your pocket working.

# Phase 8 (Cleanup)

* Fix general TODO's around the project
* Code Cleanup
* [ ] #194 
* [ ] #185 
* [ ] #165 
* [ ] #158 
* [ ] #145 
* [ ] #140 
* Write docs

**Comment by torch2424** [comment]
Benchmark was a complete success! See the medium article: https://medium.com/@torch2424/webassembly-is-fast-a-real-world-benchmark-of-webassembly-vs-es6-d85a23f8e193
