### ISSUE TITLE
Gameplan / Roadmap for Beta MVP

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasmBoy#3]
* [x] Run the bootrom, get some pixels drawn, and scroll the logo
* [x] Code Cleanup
* [x] Make a more legit debugger
* [x] Run the cpu_instructs test rom, and fix bugs
* [x] Move opcode feeding into wasm. And have js poll for when it should render. (Maybe a flag in memory?)
* [x] Get Tetris to play
* [x] [Wasmboy memory map](https://docs.google.com/spreadsheets/d/17xrEzJk5-sCB9J2mMJcVnzhbE-XH_NvczVSQH9OHvRk/edit?usp=sharing)
* [x] Rom Banking
* [x] Joypad support
* [x] Fix Graphical Bugs
* [x] Get Sound
* [x] Get In-game saves (Cartridge RAM -> IndexedDB)
* [x] Get Save States (Everything -> IndexedDB)
* [x] Beta Gameboy Color Support
* [x] Cry tears of happiness
* [x] More Optional Performance Hacks
* [x] Code Cleanup
* [x] Update the README
* [x] Get ready for publish to npm
* [x] Publish to npm
* [x] Make "frontends" for the Wasmboy lib
* [ ] Improve Accuracy / More Test Roms (With maybe some help from the community? :) )

**Comment by torch2424** [comment]
Actually, just make a should render function, pause execution until a did render is called, and repeat

**Comment by torch2424** [comment]
Closing this, now that https://github.com/torch2424/vaporBoy is nearing it's beta release 😄
